repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.0
    hooks:
    -    id: commitizen
    stages: [commit-msg]

# Setup
# > pre-commit install --hook-type commit-msg